### ISSUE TITLE
Chest UI Bug

### ISSUE THREAD

**Issue by Star1369** [Xenosaga20/Extinction-Modpack#4]
Placing 3 chests side by side will make one of them invisible and the middle visible double chest will have an extra inventory
![Chest bug](https://user-images.githubusercontent.com/41528144/55302235-ab367f80-5416-11e9-9d92-f43fa6a6a714.PNG)
![Capturar](https://user-images.githubusercontent.com/41528144/55302236-ab367f80-5416-11e9-8b04-0191501d1ec9.PNG)

.

**Comment by Embers405** [comment]
This is indeed a bug and as of right now I have no way of fixing
