### ISSUE TITLE
-Suggestions-

### ISSUE THREAD

**Issue by Star1369** [Xenosaga20/Extinction-Modpack#5]
Stone Transmutation table could have a Lower Cost

change the transmutation table on the energy condenser craft to a stone one.

Add PlusTic

Add an EMC value to Enderium Ingots

Change so that infinity Booster cards are permanent, but with a more resource intensive craft

**Comment by Embers405** [comment]
- Changed transmutation table recipe
- Don't need to add emc to enderium ingots as mystical agriculture was added
- Not going to make infinity booster cards permanent as they have an emc value and it allows you to access your ae system across dimensions
